package POJOs;
// Generated 7/11/2024 03:15:55 PM by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private Provadores provadores;
     private String nombreProducto;
     private Integer precio;

    public Productos() {
    }

    public Productos(Categoria categoria, Provadores provadores, String nombreProducto, Integer precio) {
       this.categoria = categoria;
       this.provadores = provadores;
       this.nombreProducto = nombreProducto;
       this.precio = precio;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Provadores getProvadores() {
        return this.provadores;
    }
    
    public void setProvadores(Provadores provadores) {
        this.provadores = provadores;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


