package POJOs;
// Generated 05-nov-2024 20:57:19 by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private Provadores provadores;
     private String descripcion;
     private Integer precio;

    public Productos() {
    }

    public Productos(Categoria categoria, Provadores provadores, String descripcion, Integer precio) {
       this.categoria = categoria;
       this.provadores = provadores;
       this.descripcion = descripcion;
       this.precio = precio;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Provadores getProvadores() {
        return this.provadores;
    }
    
    public void setProvadores(Provadores provadores) {
        this.provadores = provadores;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


