package POJOs;
// Generated 05-nov-2024 20:57:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provadores generated by hbm2java
 */
public class Provadores  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Provadores() {
    }

    public Provadores(String nombre, String direccion, String telefono, Set<Productos> productoses) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.productoses = productoses;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


